app/queue/views.py
from flask import Blueprint, render_template

from app import app


queue_blueprint = Blueprint('queue', __name__)


@queue_blueprint.route('/')
@queue_blueprint.route('/index')
def index():
    return render_template('index.html')

app/users/views.py
from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask_login import login_user, current_user, login_required, logout_user
from sqlalchemy.exc import IntegrityError
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime

from app import app, db, DEFAULT_TEMPLATE_DATA
from app.models import User
from app.users.forms import RegisterForm, LoginForm, EmailForm, PasswordForm
from app.emails import registration_notification, send_confirmation_email, \
    send_password_reset_email
from config import EMAIL_CONFIRM_SALT, PASSWORD_RESET_SALT
users_blueprint = Blueprint('users', __name__)


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                send_confirmation_email(new_user.email)
                flash(
                    'Регистрация аккаунта прошла успешно! На ваш электронный'
                    'адрес отравлено письмо со ссылкой для активации аккаунта.',
                    'success',
                )
                return redirect(url_for('queue.index'))
            except IntegrityError:
                db.session.rollback()
                flash(
                    'ОШИБКА! E-mail адрес ({}) уже существует в базе данных!'
                    .format(form.email.data),
                    'error',
                )
    return render_template('register.html',
                           form=form,
                           template_data={**DEFAULT_TEMPLATE_DATA,
                                          **{'title': 'Регистрация'}},
                           )


@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(
            token,
            salt=EMAIL_CONFIRM_SALT,
            max_age=3600,
        )
        user = User.query.filter_by(email=email).first()
        if user.email_confirmed:
            flash('Аккаунт уже подтвержден.', 'info')
        else:
            user.email_confirmed = True
            user.email_confirmed_on = datetime.utcnow()
            db.session.add(user)
            db.session.commit()
            flash(
                'Ваш e-mail адрес подтвержден и аккаунт активирован!',
                'success',
            )
        return redirect(url_for('queue.index'))
    except:
        flash(
            'Ссылка для подтверждения недействительна или устарела.',
            'error',
        )
        return redirect(url_for('users.login'))


@users_blueprint.route('/reset', methods=['GET', 'POST'])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            flash('Неверный адрес электронной почты.', 'error')
            return render_template('password_reset_email.html', form=form)
        if user.email_confirmed:
            send_password_reset_email(user.email)
            flash(
                'На указанный e-mail было выслано письмо с дальнейшими '
                'инструкциями.',
                'success',
            )
        else:
            flash(
                'Чтобы иметь возможность сбросить пароль Ваш e-mail адрес '
                'должен быть подтвержден. Проверьте ваш почтовый ящик на '
                'наличие письма со ссылкой для подтверждения e-mail адреса.',
                'error',
            )
        return redirect(url_for('users.login'))
    return render_template('password_reset_email.html',
                           form=form,
                           template_data={**DEFAULT_TEMPLATE_DATA,
                                          **{'title': 'Сброс пароля'}},
                           )


@users_blueprint.route('/reset/<token>', methods=['GET', 'POST'])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(
            app.config['SECRET_KEY'],
        )
        email = password_reset_serializer.loads(
            token,
            salt=PASSWORD_RESET_SALT,
            max_age=3600,
        )
    except:
        flash('Ссылка на сброс пароля неверная или устарела.', 'error')
        return redirect(url_for('users.login'))
    form = PasswordForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Неверный адрес электронной почты.', 'error')
            return redirect(url_for('users.login'))
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Пароль был успешно изменен!', 'success')
        return redirect(url_for('users.login'))
    return render_template(
        'password_change.html',
        form=form,
        form_action=url_for('users.reset_with_token', token=token),
        template_data={**DEFAULT_TEMPLATE_DATA,
                       **{'title': 'Изменение пароля'}},
    )


@users_blueprint.route('/password_change', methods=['GET', 'POST'])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('Пароль был успешно изменен!', 'success')
            return redirect(url_for('users.user_profile'))
    return render_template(
        'password_change.html',
        form=form,
        form_action=url_for('users.user_password_change'),
        template_data={**DEFAULT_TEMPLATE_DATA,
                       **{'title': 'Изменение пароля'}},
    )


@users_blueprint.route('/email_change', methods=['GET', 'POST'])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_sent_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    send_confirmation_email(user.email)
                    flash(
                        'Email адрес изменен!  Пожалуйста, подтвердите ваш '
                        'новый email адрес (письмо с интсрукциями отправлено '
                        'по почте).',
                        'success',
                    )
                    return redirect(url_for('users.user_profile'))
                else:
                    flash(
                        'Пользователь с указанным email уже существует в базе!',
                        'error',
                    )
            except IntegrityError:
                flash(
                    'Ошибка! Пользователь с указанным email уже существует в '
                    'базе!',
                    'error',
                )
    return render_template(
        'email_change.html',
        form=form,
        template_data={**DEFAULT_TEMPLATE_DATA,
                       **{'title': 'Изменение Email'}},
    )


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user is not None and current_user.is_authenticated:
        return redirect(url_for('queue.index'))
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user and user.is_correct_password(form.password.data):
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.utcnow()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                return redirect(
                    request.args.get('next') or url_for('queue.index')
                )
            else:
                flash('ОШИБКА! Неверный e-mail или пароль.', 'error')
    return render_template(
        'login.html',
        form=form,
        template_data={**DEFAULT_TEMPLATE_DATA,
                       **{'title': 'Вход'}},
    )


@users_blueprint.route('/user_profile')
@login_required
def user_profile():
    return render_template(
        'user_profile.html',
        template_data={**DEFAULT_TEMPLATE_DATA,
                       **{'title': 'Профиль пользователя'}},
    )


@users_blueprint.route('/resend_confirmation')
@login_required
def resend_email_confirmation():  # pragma: no cover
    try:
        send_confirmation_email(current_user.email)
        flash(
            'На ваш электронный адрес отравлено письмо со ссылкой для '
            'активации аккаунта.',
            'success',
        )
    except IntegrityError:
        flash(
            'Ошибка!. Не удалось отправить письмо с подверждением на ваш '
            'e-mail адрес.',
            'error',
        )
    return redirect(url_for('users.user_profile'))


@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('queue.index'))

app/templates/_form_macros.html
{% macro render_field(field) %}


<dt>{{ field.label }}:

<dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="text-danger">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
</dd>


{% endmacro %}

app/templates/base.html
<html>
<head>
    {% if template_data and template_data.get('title') and template_data.get('site_name')%}
    <title>{{template_data.get('title')}} - {{template_data.get('site_name')}}</title>
    {% elif template_data and template_data.get('site_name') %}
    <title>{{ template_data.get('site_name') }}</title>
    {% else %}
    <title>Электронная очередь</title>
    {% endif %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="navbar navbar-default">
                <div class="container">
                    <div class="navbar-header pull-left">
                        <a class="navbar-brand" href="/">
                            {% if template_data and template_data.get('site_name') %}
                            {{ template_data.get('site_name') }}
                            {% else %}
                            Электронная очередь
                            {% endif %}
                        </a>
                    </div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu" id="button_navbar_toggle">
                            <span class="sr-only">Открыть навигацию</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="responsive-menu">
                        <ul class="nav navbar-nav">
                            <li {% if (request.path == url_for('queue.index')) or  (request.path == '/') %}class="active"{% endif %}><a href="{{ url_for('queue.index') }}">Главная</a></li>
                            {% if current_user.role == "admin" %}
                            <li><a href="/admin">Админка</a></li>
                            {% endif %}
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if current_user.is_authenticated %}
                            <li {% if request.path == url_for('users.user_profile') %}class="active"{% endif %}><a href="{{ url_for('users.user_profile') }}">{{ current_user.get_username() }}</a></li>
                            <li {% if request.path == url_for('users.logout') %}class="active"{% endif %}><a href="{{ url_for('users.logout') }}">Выйти</a></li>
                            {% else %}
                            <li {% if request.path == url_for('users.register') %}class="active"{% endif %}><a href="{{ url_for('users.register') }}">Регистрация</a></li>
                            <li {% if request.path == url_for('users.login') %}class="active"{% endif %}><a href="{{ url_for('users.login') }}">Вход</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/templates/confirmation_email.html
<p>Вы были зарегистрированы на сайте <a href="{{url_for('queue.index', _external = True)}}">"Электронная очередь"</a>.</p>
<p>Для подтверждения e-mail адреса и активации аккаунта перейдите по ссылке: <a href="{{ confirm_url }}">{{ confirm_url }}</a>.</p>

С уважением,

Администратор сайта "Электронная очередь"

app/templates/email_change.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
{% include 'flash.html' %}
<div class="user-profile">
  <div class="page-header">
    <h2>Изменить Email</h2>
  </div>
  <h4>Текущий Email: {{ current_user.email }}</h4>
  <h4>Новый Email:</h4>
  <form action="{{ url_for('users.user_email_change') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Введите новый Email адрес") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Обновить</button>
  </form>
</div>

{% endblock %}

app/templates/email_password_reset.html
<p>Вами была запрошена процедура сброса пароля на сайте  <a href="{{url_for('queue.index', _external = True)}}">"Электронная очередь"</a>.</p>
<p>Для сброса пароля перейдите по ссылке: <a href="{{ password_reset_url }}">{{ password_reset_url }}</a> или проигнорируйте это письмо, если вы не запрашивали сброс пароля.</p>

С уважением,

Администратор сайта "Электронная очередь"

app/templates/flash.html
<!-- flash messages -->
{% for error_message in get_flashed_messages(category_filter=["error"]) %}
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">×</button>
    {{ error_message }}
</div>
{% endfor %}
{% for success_message in get_flashed_messages(category_filter=["success"]) %}
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">×</button>
    {{ success_message }}
</div>
{% endfor %}
{% for info_message in get_flashed_messages(category_filter=["info"]) %}
<div class="alert alert-info alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">×</button>
    {{ info_message }}
</div>
{% endfor %}

app/templates/index.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
{% include 'flash.html' %}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
{% include 'flash.html' %}
<div class="user-registration">
  <div class="page-header">
    <h2>Вход</h2>
  </div>
    <form action="{{ url_for('users.login', next=request.args.get('next')) }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="E-mail адрес") }}
      {{ render_field(form.password, placeholder="Пароль") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Войти</button>
  </form>
  <em>Нет аккаунта? </em><a href="{{ url_for('users.register') }}">Зарегистрируйся!</a>
  | <em>Забыли пароль? </em><a href="{{ url_for('users.reset') }}">Восстановить!</a>
</div>
{% endblock %}

app/templates/password_change.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
{% include 'flash.html' %}
<div class="add-recipe">
  <div class="page-header">
    <h2>Новый пароль</h2>
  </div>
  <form action="{{ form_action }}" method="POST">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Новый пароль") }}
      {{ render_field(form.confirm, placeholder="Повторите пароль") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Изменить пароль</button>
  </form>
</div>

{% endblock %}

app/templates/password_reset_email.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
{% include 'flash.html' %}
<div class="add-recipe">
  <div class="page-header">
    <h2>Сброс пароля</h2>
  </div>
  <form action="{{ url_for('users.reset') }}" method="POST">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="E-mail адрес") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Сбросить пароль</button>
  </form>
</div>

{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
{% include 'flash.html' %}
<div class="user-registration">
  <div class="page-header">
    <h2>Регистрация нового акканунта</h2>
  </div>
<form action="{{ url_for('users.register') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="E-mail адрес") }}
      {{ render_field(form.password, placeholder="Пароль") }}
      {{ render_field(form.confirm, placeholder="Повторите пароль") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Создать новый аккаунт</button>
  </form>
  <em>Уже есть аккаунт? </em><a href="{{ url_for('users.login') }}">Войти!</a>
</div>
{% endblock %}

app/templates/registration_email.html
<p>{{user.email}}, Вы успешно зарегистрировались на сайте <a href="{{ url_for('queue.index', _external=True) }}">"Электронная очередь"</a>.</p>
<p>Для перехода в личный кабинет воспользуйтесь ссылкой:</p>
<p>С уважением,</p>
<p>Администратор сайта <code>"Электронная очередь"</code></p>

app/templates/user_profile.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
{% include 'flash.html' %}
<div class="user-profile">
  <div class="page-header">
    <h2>Профиль пользователя</h2>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-primary">
        {% if current_user.get_username() != current_user.email %}
          <div class="panel-heading">Пользователь</div>
          <div class="panel-body">{{ current_user.get_username() }}</div>
        {% endif %}
          <div class="panel-heading">Email адрес</div>
          <div class="panel-body">{{ current_user.email }}</div>
        {% if current_user.role != 'user' %}
          <div class="panel-heading">Роль</div>
          <div class="panel-body">{{ current_user.role }}</div>
        {% endif %}
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Действия с аккаунтом</div>
        <div class="panel-body"><a href="{{ url_for('users.user_email_change') }}">Изменить email</a></div>
        <div class="panel-body"><a href="{{ url_for('users.user_password_change') }}">Изменить пароль</a></div>
        {% if not current_user.email_confirmed %}
          <div class="panel-body"><a href="{{ url_for('users.resend_email_confirmation') }}">Повторно отправить письмо для подтверждения email адреса</a></div>
        {% endif %}
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Статистика</div>
        <div class="panel-body">Зарегистрирован: {{ current_user.registered_on.strftime("%d %B %Y %H:%M") }}</div>
        {% if current_user.last_logged_in != None %}
          <div class="panel-body">Последний вход: {{ current_user.last_logged_in.strftime("%d %B %Y %H:%M") }}</div>
        {% else %}
          <div class="panel-body">Первый вход в систему. Добро пожаловать!</div>
        {% endif %}
        {% if current_user.email_confirmed %}
          <div class="panel-body">Email адрес подтвержден: {{ current_user.email_confirmed_on.strftime("%d %B %Y%H:%M") }}</div>
        {% else %}
          <div class="panel-body">Email ардес не подтвержден!</div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}